### ISSUE TITLE
Got problems when running the app

### ISSUE THREAD

**Issue by lengjunxiaogudy** [raj10071997/Alexa-Voice-Service#11]
hello raj10071997,
    It is my honor to study your project. When i run the app, the mainactivity and the browser take turns showing in front of screen and i just cannot stop them unless i kill the process. It must be wrong somewhere. If i want to run the app, do i only need to register the api_key.txt and the security profile? I guess that i made some mistakes during creating the api key and security profile. For example, i used my own PC's MD5 and SHA256 and changed PRODUCT_ID in mainactivity with my own. What else should i pay attention to? Thanks for your help!

**Comment by raj10071997** [comment]
Have you registered your security profile for Login with Amazon?

**Comment by lengjunxiaogudy** [comment]
Yes. Should i completely follow the steps https://github.com/alexa/alexa-avs-sample-app/wiki/Create-Security-Profile
to create a security profile? The app runs in android phones, so i just choose "application", not "device".

**Comment by raj10071997** [comment]
You can choose any option as an android phone can also be treated as a device. If you are just creating a security profile as given in the above link then it is possible that you have not enabled your security profile although you have created it. Here's the [link](https://developer.amazon.com/lwa/sp/overview.html). If you have enabled it, then it might be because of that "application" option. Try with "device" option

**Comment by lengjunxiaogudy** [comment]
Thank you for your reply. I have enabled the security profile after i created it. Logcat shows that "ThirdPartyServiceHelper: Returning no service to use" and some information like that. Compared with the app, amazon official login_with_amazon example shall open a website for user to fill in account information or click back button. It seems like that, the app is automatically, continously checking my account information but gives me no chance to input anything. So, it takes turns showing mainactivity and the login website in front of screen.

**Comment by raj10071997** [comment]
Sorry for the late reply. The app is not filling your info automatically. And yes  according to official login_with_amazon , the website has to be opened in a browser as it implemented in the login with amazon library. If it is happening with you then please send me a screenshot or a gif of the issue so that I can better understand the issue and improve my app for that problem. Thanks in advance.
